### ISSUE TITLE
Mohist 1.20.1 and plugins Typewriter

### ISSUE THREAD

**Issue by NeverPixel** [Shynixn/MCCoroutine#112]
здравствуйте, увидел ваш плагин на spigot, и заметил там такую штуку как имитирование async,await в Bukkit, и вот хотел бы узнать, это ошибка или нет
так то все работает в плагине на гибритке только что выстакивают две вот такие ошибки хотя я юзаю ваш плагин.

[21:36:24 WARN]: Legacy plugin MCCoroutine-Sample v2.15.0 does not specify an api-version.
[21:36:25 INFO]: [Typewriter] Loading 4 libraries... please wait
[21:36:25 INFO]: [Typewriter] Loading 18 extra libraries... please wait
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.7.1/kotlinx-coroutines-core-1.7.1.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/annotations/13.0/annotations-13.0.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-codec/4.1.63.Final/netty-codec-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/com/corundumstudio/socketio/netty-socketio/1.7.19/netty-socketio-1.7.19.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-buffer/4.1.63.Final/netty-buffer-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-handler/4.1.63.Final/netty-handler-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.20/kotlin-stdlib-jdk8-1.8.20.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.20/kotlin-stdlib-jdk7-1.8.20.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-resolver/4.1.63.Final/netty-resolver-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlin/kotlin-reflect/1.9.22/kotlin-reflect-1.9.22.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlin/kotlin-stdlib/1.9.22/kotlin-stdlib-1.9.22.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-transport-native-epoll/4.1.63.Final/netty-transport-native-epoll-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.20/kotlin-stdlib-common-1.8.20.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-transport-native-unix-common/4.1.63.Final/netty-transport-native-unix-common-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-transport/4.1.63.Final/netty-transport-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-common/4.1.63.Final/netty-common-4.1.63.Final.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.7.1/kotlinx-coroutines-core-jvm-1.7.1.jar
[21:36:25 INFO]: [Typewriter] Loaded libraries libraries/plugins-lib/io/netty/netty-codec-http/4.1.63.Final/netty-codec-http-4.1.63.Final.jar
[21:36:26 INFO]: [MCCoroutine-Sample] Loading MCCoroutine-Sample v2.15.0
[21:36:26 INFO]: [ProtocolLib] Loading ProtocolLib v5.2.0-SNAPSHOT-679
[21:36:30 INFO]: [packetevents] Loading packetevents v2.2.1
[21:36:31 INFO]: [Typewriter] Loading Typewriter v0.4.2
[21:36:32 INFO]: [Typewriter] Loading adapter BasicAdapter
[21:36:36 WARN]: [Typewriter] Regex annotation can only be used on strings (including in lists or maps)!
[21:36:36 ERROR]: io/papermc/paper/event/player/AsyncChatEvent initializing Typewriter v0.4.2 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/event/player/AsyncChatEvent
        at com.mohistmc.bukkit.remapping.ClassLoaderRemapper.tryDefineClass(ClassLoaderRemapper.java:173) ~[forge-1.20.1-47.2.23-universal.jar%23201!/:?]
        at com.mohistmc.bukkit.remapping.ReflectionHandler_3.redirectGetMethods(ReflectionHandler.java:61) ~[forge-1.20.1-47.2.23-universal.jar%23201!/:?]
        at me.gabber235.typewriter.adapters.AdapterListeners$constructAdapterListeners$1.invoke(AdapterListeners.kt:77) ~[?:?]
        at me.gabber235.typewriter.adapters.AdapterListeners$constructAdapterListeners$1.invoke(AdapterListeners.kt:77) ~[?:?]
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315) ~[?:?]
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303) ~[?:?]
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169) ~[?:?]
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[?:?]
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169) ~[?:?]
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[?:?]
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214) ~[?:?]
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:816) ~[?:?]
        at me.gabber235.typewriter.adapters.AdapterListeners.constructAdapterListeners(AdapterListeners.kt:81) ~[?:?]
        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.constructAdapter(AdapterLoader.kt:176) ~[?:?]
        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.loadAdapter(AdapterLoader.kt:156) ~[?:?]
        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.loadAdapters(AdapterLoader.kt:75) ~[?:?]
        at me.gabber235.typewriter.Typewriter.onLoad(Typewriter.kt:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.23-universal.jar%23201!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        
        
[21:36:46 INFO]: [MCCoroutine-Sample] Enabling MCCoroutine-Sample v2.15.0
[21:36:46 INFO]: [MCCoroutineSamplePlugin/onEnableAsync] Is starting on Thread:Server thread/49/primaryThread=true
[21:36:46 INFO]: [MCCoroutineSamplePlugin/onEnableAsync] Simulating data load Thread:DefaultDispatcher-worker-1/65/primaryThread=false
[21:36:46 INFO]: [MCCoroutineSamplePlugin/onEnableAsync] Is ending on Thread:Server thread/49/primaryThread=true
[21:36:46 INFO]: [packetevents] Enabling packetevents v2.2.1
[21:36:46 INFO]: [packetevents] Checking for updates, please wait...
[21:36:46 INFO]: [Typewriter] Enabling Typewriter v0.4.2
[21:36:47 INFO]: [packetevents] You are on the latest released version of packetevents. Your build: (2.2.1)
[21:36:47 INFO]: [Mohist] Enabling Mohist v1.20.1
[21:36:47 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:36:47 INFO]: Done (11.264s)! For help, type "help"
container@nookure~  Server marked as running...
[21:36:47 INFO]: Successfully initialized permission handler forge:default_handler
[21:36:47 INFO]: Forwarding forge permission[forge:default_handler] to bukkit[mohist:permission]
[21:36:47 INFO]: [Typewriter] Loaded 0 entries from 0 pages.
[21:36:53 ERROR]: [Typewriter] This is not an error of MCCoroutine! See sub exception for details.
java.lang.NoSuchMethodError: 'io.papermc.paper.plugin.configuration.PluginMeta org.bukkit.plugin.Plugin.getPluginMeta()'
        at me.gabber235.typewriter.extensions.modrinth.Modrinth.findLatestVersion(Modrinth.kt:77) ~[?:?]
        at me.gabber235.typewriter.extensions.modrinth.Modrinth.loadVersion(Modrinth.kt:56) ~[?:?]
        at me.gabber235.typewriter.extensions.modrinth.Modrinth.access$loadVersion(Modrinth.kt:23) ~[?:?]
        at me.gabber235.typewriter.extensions.modrinth.Modrinth$loadVersion$1.invokeSuspend(Modrinth.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.2.23-universal.jar%23201!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.2.23-universal.jar%23201!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1133) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1072) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:902) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Shynixn** [comment]
What are you even doing? 

* Speak English please
* MCCoroutine-Sample is (as the name indicates) an example plugin. Do not use it in production on your server.
* Open an issue for the Typewriter plugin. Not here, this is the wrong repository.

```
 ([21:36:53 ERROR]: [Typewriter] This is not an error of MCCoroutine! See sub exception for details.) 
```
