### ISSUE TITLE
NoSuchMethodException on latest velocity build

### ISSUE THREAD

**Issue by Syrent** [Shynixn/MCCoroutine#125]
The latest version of Velocity throws an error when I try to initialize `SuspendingPluginContainer`, but it works fine with older versions of Velocity. The error message is as follows:

```
[12:43:02 ERROR]: Couldn't pass ProxyInitializeEvent to sayanvanish 1.5.0-SNAPSHOT-build.dev-local
java.lang.NoSuchMethodException: com.velocitypowered.proxy.event.VelocityEventManager$HandlerRegistration.<init>(com.velocitypowered.api.plugin.PluginContainer,short,java.lang.Class,java.lang.Object,com.velocitypowered.api.event.EventHandler)
	at java.base/java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at com.github.shynixn.mccoroutine.velocity.service.EventServiceImpl.registerInternally(EventServiceImpl.kt:68) ~[?:?]
	at com.github.shynixn.mccoroutine.velocity.service.EventServiceImpl.registerListener(EventServiceImpl.kt:26) ~[?:?]
	at com.github.shynixn.mccoroutine.velocity.impl.CoroutineSessionImpl.registerSuspendListener(CoroutineSessionImpl.kt:70) ~[?:?]
	at com.github.shynixn.mccoroutine.velocity.SuspendingPluginContainer.initialize(SuspendingPluginContainer.kt:45) ~[?:?]
	at org.sayandev.sayanvanish.velocity.SayanVanish.onProxyInitialize(SayanVanish.kt:40) ~[?:?]
	at org.sayandev.sayanvanish.velocity.Lmbda$6.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

I suspect it might be related to [this commit](https://github.com/PaperMC/Velocity/commit/4f227badc20dc30b0f6d84b5349c8809481dcbb1). However, in this update, the previous method is deprecated, not removed, so I'm not sure why there's a `NoSuchMethodException`.

**Comment by Syrent** [comment]
Any updates on this? I tried compiling the project myself, but each module requires a different version of Java, and I’m not sure how to manage that. It would be really helpful if you could take a look and resolve the issue.
